tap "deviceinsight/packages"
brew "deviceinsight/packages/kafkactl"

tap "oktadeveloper/tap"
cask "okta"

# basic system customization
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
brew "fish"
brew "starship"

tap "cmacrae/formulae"
brew "cmacrae/formulae/spacebar"

tap "nikitabobko/tap"
cask "nikitabobko/tap/aerospace"

# dev tools
brew "coreutils"
brew "difftastic"
brew "duckdb"
brew "fzf"
brew "git"
brew "gnupg"
brew "gnutls"
brew "go@1.20"
brew "golang-migrate"
brew "gopls"
brew "gotestsum"
brew "jj"
brew "jq"
brew "lazygit"
brew "librdkafka"
brew "neovim"
brew "openssl@3"
brew "poetry"
brew "postgresql@15"
brew "protobuf"
brew "pyright"
brew "python@3.12"
brew "readline"
brew "redis"
brew "ripgrep"
brew "wget"

cask "podman-desktop"

cask "1password"
cask "1password-cli"
cask "gimp"
cask "hoppscotch"
