#!/usr/bin/env lua

function table.diff(t1, t2)
  local diff = {}
  for k, v in pairs(t1) do
    if t2[k] ~= v then
      diff[k] = v
    end
  end
  return diff
end

function table.inspect(t)
  local s = "{ "
  for k, v in pairs(t) do
    if type(v) == "table" then
      s = s .. k .. " = " .. table.inspect(v) .. ", "
    else
      s = s .. k .. " = " .. tostring(v) .. ", "
    end
  end
  s = s .. " }"
  return s
end

function string.split(s, sep)
  sep = sep or "\n"

  local t = {}
  for str in string.gmatch(s, "([^"..sep.."]+)") do
    table.insert(t, str)
  end
  return t
end

sbar = require("sketchybar")

sbar.begin_config()

local theme = require("theme")

sbar.bar({
  position = "top",
  margin = 8,
  y_offset = 5,
  height = 28,
  corner_radius = 14,
  blur_radius=30,
  color = theme.colors.bg,
  border_color = theme.colors.bg,
  border_width = 1,
  shadow = false,
  sticky = true,
})

sbar.default({
  padding_left=3,
  padding_right=3,
  icon = {
    color=theme.colors.fg,
    font="Hack Nerd Font:Bold:16.0",
  },
  label = {
    color=theme.colors.fg,
    font="SF Pro:Bold:12.0",
  },
  updates="on",
})

require("aerospace")
require("clock")

sbar.hotload(true)
sbar.end_config()

sbar.event_loop()
